### ISSUE TITLE
Ошибка при локальном импорте

### ISSUE THREAD

**Issue by Sa1ch** [yzen-dev/vue-dadata-suggestions#1]
Здравствуйте! Если импортировать компонент локально то в консоли появляется ошибка:

> [Vue warn]: Failed to mount component: template or render function not defined.

И инпут не отображается в шаблоне.

**Comment by yzen-dev** [comment]
Добрый день! На этой неделе постараюсь заняться вашей проблемой. 
Если не сложно, могли бы еще отправить пример, как именно вы подключаете компонент.

**Comment by yzen-dev** [comment]
Добрый день! Как именно вы "импортировали" его локально? Там есть обязательный файл dadata.js и jquery в зависимостях.

В ближайшее время будет настроена сборка бандла, надеюсь это решит вашу проблему.
