### ISSUE TITLE
Constraints support

### ISSUE THREAD

**Issue by keen-on-design** [yzen-dev/vue-dadata-suggestions#2]
Does this package support constraints? Jquery example: https://codepen.io/dadata/pen/cGkah 
In given example city field is bound to region 
`$city.suggestions({
  token: token,
  type: type,
  hint: false,
  bounds: "city-settlement",
  constraints: $region,
  formatSelected: formatCity
});`

**Comment by yzen-dev** [comment]
Добрый день! В данный момент такой возможности нет.
Кажется это будет полезной доработкой, так что в ближайшее время я займусь этим вопросом.

**Comment by yzen-dev** [comment]
В данный момент через компонент не получится такое реализовать. Но т.к. в пакете используется скрипт dadata, то у вас может это получится. Если у вас в проекте используется jquery, то прописав свой options, вы там можете попробовать указать constraints: $('el').

Планируется удаление зависимости от jquery, и свое написание всех запросов к dadata. Так что потом я вернусь к этому вопросу.
