### ISSUE TITLE
Как исправить ошибку при вводе другого type

### ISSUE THREAD

**Issue by korotkovaan** [yzen-dev/vue-dadata-suggestions#4]
Ввозу допустим `type="fms_unit"`
И мне выдает ошибку.. 
как ее обойти? 
![image](https://user-images.githubusercontent.com/64261702/106457809-91e23c80-64a0-11eb-8492-fd39f809ae57.png)

**Comment by yzen-dev** [comment]
Добрый день! Возможно, у вашего токена нет доступа к данному методу. 
Проверил сейчас данный типа - ошибок не обнаружено.
![image](https://user-images.githubusercontent.com/24630195/106566898-04572900-6542-11eb-8d9d-7fc32d9decb6.png)

Вот пример рабочего кода:
https://codesandbox.io/s/test-vue-dadata-suggestions-ri6wc?file=/src/App.vue

Только в main.js укажите ваш токен.

**Comment by korotkovaan** [comment]
Спасибо, действительно что-то было с токеном. Заменил его и все ок, работает как часы. 
Подскажите еще один момент. 
При type: PARTY 
Мы получаем всю доступную инфу по Организации. 
Как вывести Полное наименование организации в поле ввода, то есть вместо field-value="unrestricted_value", мне надо field-value="full_with_opf", но это поле находится не в data, поля из data выводятся.

**Comment by yzen-dev** [comment]
Привет.
@korotkovaan , теперь такая возможность есть.
https://github.com/yzen-dev/vue-dadata-suggestions/releases/tag/0.6.0

Теперь ты можешь сделать вот так:
```
<dadata-suggestions
    v-model="full_name"
    fieldValue="name.full_with_opf"
    type="PARTY"
 />
```
